/**
 * Service worker: makes the game installable and playable with no network.
 *
 * Two strategies, split by what the file is:
 *
 *   code and markup (.html, .js, the manifest)  -> network first, cache fallback
 *   art and icons (.png)                        -> cache first
 *
 * Cache-first for everything is the usual advice and it is wrong here. The
 * sprites never change, so caching them forever is free; the JavaScript changes
 * every build, and a cache-first worker will happily serve last week's game to
 * a player who is online and has just been shipped a fix. Network-first costs
 * one round trip when online and still works fully offline.
 */

const CACHE = 'bhrd-v7';

/** How long to wait for the network before falling back to the cache [ms]. */
const NETWORK_TIMEOUT_MS = 2500;

/** Files whose contents change from build to build. */
const isCode = (url) =>
  url.pathname.endsWith('.js')
  || url.pathname.endsWith('.html')
  || url.pathname.endsWith('.webmanifest')
  || url.pathname === '/'
  || url.pathname.endsWith('/');

// >>> generated by tools/make_sw_manifest.py — do not edit by hand
const PRECACHE = [
  './',
  './index.html',
  './manifest.webmanifest',
  './dist/src/audio/sfx.js',
  './dist/src/core/ability.js',
  './dist/src/core/bat.js',
  './dist/src/core/bats.js',
  './dist/src/core/constants.js',
  './dist/src/core/game.js',
  './dist/src/core/level.js',
  './dist/src/core/physics.js',
  './dist/src/core/pitch.js',
  './dist/src/core/pitchers.js',
  './dist/src/core/ranks.js',
  './dist/src/core/rng.js',
  './dist/src/core/round.js',
  './dist/src/core/stadium.js',
  './dist/src/core/vec.js',
  './dist/src/main.js',
  './dist/src/render/batter.js',
  './dist/src/render/camera.js',
  './dist/src/render/figure.js',
  './dist/src/render/fx.js',
  './dist/src/render/hud.js',
  './dist/src/render/pitcher.js',
  './dist/src/render/scene.js',
  './dist/src/render/screens.js',
  './dist/src/render/stadium.js',
  './dist/src/storage.js',
  './assets/face/atsushi_angle.png',
  './assets/face/atsushi_bust.png',
  './assets/face/atsushi_front.png',
  './assets/face/atsushi_profile.png',
  './assets/face/atsushi_relief.png',
  './assets/face/atsushi_serious.png',
  './assets/face/atsushi_smile.png',
  './assets/face/atsushi_thinking.png',
  './assets/face/takaya_angle.png',
  './assets/face/takaya_bust.png',
  './assets/face/takaya_front.png',
  './assets/face/takaya_profile.png',
  './assets/face/takaya_relief.png',
  './assets/face/takaya_serious.png',
  './assets/face/takaya_smile.png',
  './assets/face/takaya_thinking.png',
  './assets/face/yuki_angle.png',
  './assets/face/yuki_bust.png',
  './assets/face/yuki_front.png',
  './assets/face/yuki_profile.png',
  './assets/face/yuki_relief.png',
  './assets/face/yuki_serious.png',
  './assets/face/yuki_smile.png',
  './assets/face/yuki_thinking.png',
  './assets/icon/icon-192.png',
  './assets/icon/icon-512.png',
  './assets/icon/icon-maskable-512.png',
  './assets/logo_back.png',
  './assets/player/anchors.json',
  './assets/player/atsushi/back.png',
  './assets/player/atsushi/back_cam.png',
  './assets/player/atsushi/back_cam_bat.png',
  './assets/player/atsushi/back_cam_body.png',
  './assets/player/atsushi/stance.png',
  './assets/player/atsushi/swing_0.png',
  './assets/player/atsushi/swing_1.png',
  './assets/player/atsushi/swing_2.png',
  './assets/player/atsushi/swing_3.png',
  './assets/player/atsushi/swing_4.png',
  './assets/player/bat_anchors.json',
  './assets/player/takaya/back.png',
  './assets/player/takaya/back_cam.png',
  './assets/player/takaya/back_cam_bat.png',
  './assets/player/takaya/back_cam_body.png',
  './assets/player/takaya/stance.png',
  './assets/player/takaya/swing_0.png',
  './assets/player/takaya/swing_1.png',
  './assets/player/takaya/swing_2.png',
  './assets/player/takaya/swing_3.png',
  './assets/player/takaya/swing_4.png',
  './assets/player/yuki/back.png',
  './assets/player/yuki/back_cam.png',
  './assets/player/yuki/back_cam_bat.png',
  './assets/player/yuki/back_cam_body.png',
  './assets/player/yuki/stance.png',
  './assets/player/yuki/swing_0.png',
  './assets/player/yuki/swing_1.png',
  './assets/player/yuki/swing_2.png',
  './assets/player/yuki/swing_3.png',
  './assets/player/yuki/swing_4.png',
];
// <<< generated

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // addAll is atomic: one 404 and nothing is cached, which is the behaviour we
    // want — a half-cached game that boots and then fails is worse than no cache.
    await cache.addAll(PRECACHE);
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(names.filter((n) => n !== CACHE).map((n) => caches.delete(n)));
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  const remember = async (response) => {
    if (response && response.ok && response.type === 'basic') {
      const cache = await caches.open(CACHE);
      await cache.put(request, response.clone());
    }
    return response;
  };

  if (isCode(url) || request.mode === 'navigate') {
    event.respondWith((async () => {
      try {
        // Race the network against a short timer.
        //
        // Offline, fetch rejects quickly and the catch below serves the cache.
        // On a bad mobile connection — a train, a car park, a hotel captive
        // portal — it does not reject at all: it hangs, and the game sits on a
        // black screen for thirty seconds while a cached copy of everything it
        // needs is sitting on the device. Whichever answers first wins.
        const response = await Promise.race([
          fetch(request),
          new Promise((_, reject) =>
            setTimeout(() => reject(new Error('slow network')), NETWORK_TIMEOUT_MS)),
        ]);
        return await remember(response);
      } catch (err) {
        const cached = await caches.match(request, { ignoreSearch: true });
        if (cached) return cached;
        if (request.mode === 'navigate') {
          const shell = await caches.match('./index.html');
          if (shell) return shell;
        }
        throw err;
      }
    })());
    return;
  }

  event.respondWith((async () => {
    const cached = await caches.match(request, { ignoreSearch: true });
    if (cached) return cached;
    return remember(await fetch(request));
  })());
});
