"""
Regenerate the service worker's precache list from what is actually on disk.

    npm run build && python tools/make_sw_manifest.py

Why this is generated rather than written by hand. `cache.addAll` is atomic: if
one entry 404s, NOTHING is cached and the game simply does not start without a
network. The list was hand-maintained and had silently fallen four modules and
twenty-five images behind, which meant the installed app was not actually
playable offline — the one thing a service worker exists to do, failing
invisibly, because online it all works.

tests/offline.test.ts checks the result, so the list cannot rot again without a
test going red.
"""

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SW = ROOT / "sw.js"

BEGIN = "// >>> generated by tools/make_sw_manifest.py — do not edit by hand"
END = "// <<< generated"


def collect():
    out = ["./", "./index.html", "./manifest.webmanifest"]

    js = sorted(
        p.relative_to(ROOT).as_posix()
        for p in (ROOT / "dist" / "src").rglob("*.js")
    )
    if not js:
        sys.exit("dist/src has no .js — run `npm run build` first")
    out += ["./" + p for p in js]

    # assets/src holds the original sheets the extractor reads. The game never
    # loads them, they are the largest files in the tree, and shipping them would
    # put four megabytes into every phone's cache for nothing. Worse: they are
    # build INPUT, so a deployment that ships only what the game needs would not
    # have them, and addAll being atomic means the whole cache would fail.
    art = sorted(
        p.relative_to(ROOT).as_posix()
        for p in (ROOT / "assets").rglob("*")
        if p.is_file()
        and p.suffix.lower() in {".png", ".json"}
        and "assets/src/" not in p.relative_to(ROOT).as_posix()
    )
    out += ["./" + p for p in art]
    return out


def main():
    files = collect()
    body = "\n".join("  '%s'," % f for f in files)
    block = "%s\nconst PRECACHE = [\n%s\n];\n%s" % (BEGIN, body, END)

    text = SW.read_text(encoding="utf-8")
    if BEGIN in text and END in text:
        head = text[: text.index(BEGIN)]
        tail = text[text.index(END) + len(END) :]
        text = head + block + tail
    else:
        sys.exit("markers not found in sw.js; add them around the PRECACHE array")

    SW.write_text(text, encoding="utf-8")
    print("precache: %d entries (%d js, %d art)" % (
        len(files),
        sum(1 for f in files if f.endswith(".js")),
        sum(1 for f in files if f.endswith((".png", ".json"))),
    ))


if __name__ == "__main__":
    main()
